version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/wikipedia_db  # Use container name as hostname
    depends_on:
      - mongodb
    extra_hosts:
      - "host.docker.internal:host-gateway"


  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:

networks:
  mynetwork:
    driver: bridge
